#ifndef TATR_API_H_
#define TATR_API_H_

#include <stdint.h>
#include <stdbool.h>

#include "error.h"
#include "issue.h"
#include "render.h"

// Load issue `id` and assemble it into a Tatr_Issue_View.
// If `raw`, only the raw/raw_mode fields of `out` are populated.
// String_Views in `out` (and the attachments array) are temp-allocated
// and are valid until the caller's temp checkpoint is rewound.
Tatr_Error tatr_issue_show(const char *id, bool raw, Tatr_Issue_View *out);

typedef struct {
    Issue_Status_Kind   status;   // ISSUE_SINVALID = no filter  
    Issue_Priority_Kind priority; // ISSUE_PINVALID = no filter  
    const char         *tag;      // NULL = no filter            
    bool                include_closed;
    uint64_t            limit;    // 0 = unlimited               
} Tatr_Issue_Filter;

// List issues matching `filter`, in the same order `tatr list` has
// always used (sorted by id). Entries in *out are temp-allocated.
Tatr_Error tatr_issue_list(const Tatr_Issue_Filter *filter, bool show_header, Tatr_Issue_List_Result *out);

const char *tatr_version(void);

// ---- tatr_issue_attachments: `tatr attachls` ----

Tatr_Error tatr_issue_attachments(const char *id, Tatr_Attachment_List_Result *out);

// ---- tatr_issue_search: `tatr search` ----

typedef struct {
    const char *const *tokens; // as given on argv, e.g. "tag:backend", "crash"
    size_t token_count;
    bool case_sensitive;
    bool header_only;
    uint64_t limit; // 0 = unlimited
} Tatr_Search_Query;

Tatr_Error tatr_issue_search(const Tatr_Search_Query *q, Tatr_Search_Result *out);

// ---- tatr_log_query: `tatr log` ----

typedef struct {
    const char *id_prefix; // NULL/"" = no filter
    const char *event;     // NULL/"" = no filter
    const char *author;    // NULL/"" = no filter
    time_t since;          // 0 = no filter
    time_t until;          // 0 = no filter
    bool reverse;          // oldest first
    bool oneline;
    uint64_t limit;        // 0 = unlimited
} Tatr_Log_Query;

Tatr_Error tatr_log_query(const Tatr_Log_Query *q, TatrLog_Entries *entries, Tatr_Log_Result *out);

// ---- tatr_status: `tatr status` ----

typedef struct {
    uint64_t recent_limit;
    uint64_t stale_days;
} Tatr_Status_Query;

// Entries in *out are temp-allocated.
Tatr_Error tatr_status(const Tatr_Status_Query *q, Tatr_Status_Result *out);

// ---- tatr_config_list / tatr_config_keys: `tatr config --list` / `--keys` ----

// show_local/show_global mirror the CLI's --local/--global flags
// if both are false, all three sections (local, global, resolved) are shown.
Tatr_Error tatr_config_list(const Config *c, bool show_local, bool show_global, Tatr_Config_List_Result *out);

void tatr_config_keys(Tatr_Config_Keys_Result *out);

// ---- Mutating operations ----

Tatr_Error tatr_issue_close(const char *id, const char *reason, const char *author);
Tatr_Error tatr_issue_reopen(const char *id, const char *author);

Tatr_Error tatr_issue_delete_one(const char *id, const char *author, String_View *out_title);
Tatr_Error tatr_issue_add_comment(const char *id, const char *text, const char *author);

typedef struct {
    const char *const *tags;
    size_t count;
    bool remove;
} Tatr_Tag_Request;

Tatr_Error tatr_issue_tag(const char *id, const Tatr_Tag_Request *req, const char *author, const char **out_conflict_tag);

typedef struct {
    bool renamed;         // true if dst_name differs from the source's basename
    const char *dst_name; // final on-disk filename, temp-allocated
} Tatr_Attach_Result;

// Copies `src_path` into issue `id`'s attachments/, renaming on conflict.
Tatr_Error tatr_issue_attach(const char *id, const char *src_path, const char *author,
                              Tatr_Attach_Result *out);

// Removes attachment `filename` from issue `id`.
//   TATR_ERR_NOT_FOUND - no such attachment
Tatr_Error tatr_issue_detach(const char *id, const char *filename, const char *author);

// Sets `field` ("title"/"status"/"priority"/"tags"/"body") to `value` directly (the non-editor edit path).
//   TATR_ERR_CONFLICT - value is unchanged (no-op, not saved)
Tatr_Error tatr_issue_edit_field(const char *id, const char *field, const char *value, const char *author, String_View *out_old);

// Persists a raw, already-edited issue body
Tatr_Error tatr_issue_save_edited(Issue *iss, const char *author);

typedef struct {
    const char *id;       // pre-generated by the caller
    const char *title;    // may be NULL/empty
    const char *status;   // e.g. "open"
    const char *priority; // e.g. "normal"
    const char *tags_csv; // comma-joined, may be NULL/empty
    String_View body;     // may be empty (count == 0)
                          // null-terminated
    const char *author;
} Tatr_Issue_New_Params;

Tatr_Error tatr_issue_new(const Tatr_Issue_New_Params *p, Issue *iss);
Tatr_Error tatr_issue_new_from_editor(Issue *iss, const char *id, const char *author);

#endif // TATR_API_H_
