name: Tatr Build

on:
  push:
    branches: [ master ]
  pull_request:

jobs:
  macos:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4

      - name: Build + Install + Test
        run: |
          make BUILD=Release WARNINGS=1 -j
          sudo make install PREFIX=/usr/local

          make clean
          make BUILD=Debug ASAN=1 UBSAN=1 -j

          cd tests
          make

  ubuntu:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        cc: [gcc, clang]

    steps:
      - uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential clang make

      - name: Build + Install + Test
        env:
          CC: ${{ matrix.cc }}
        run: |
          make BUILD=Release WARNINGS=1 -j
          sudo make install PREFIX=/usr/local

          make clean
          make BUILD=Debug ASAN=1 UBSAN=1 -j

          cd tests
          make

  windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup MSYS2
        uses: msys2/setup-msys2@v2
        with:
          msystem: MINGW64
          update: true
          install: >
            mingw-w64-x86_64-gcc
            make

      - name: Build + Install + Test
        shell: msys2 {0}
        run: |
          make BUILD=Release WARNINGS=1 -j
          make install PREFIX=/mingw64

          make clean
          make BUILD=Debug -j

          cd tests
          make
